### ISSUE TITLE
Allow configuring a default CA certificate file

### ISSUE THREAD

**Issue by bfad** [elixir-mint/mint#229]
I would like to be able to specify the location of the certificate file that is managed by my OS. It would be great if I could configure Mint to use that by default instead of having to pass that option every time I call `connect`.

I would like to be able to have the following code in my `config/config.exs` file:
```elixir
config Mint, :cacertfile, "/etc/ssl/certs/ca-certificates.crt"
```
And then I would like all SSL connections to use that file unless the call to `connect` specified something different.

I don't mind trying to implement this, but I figured I'd create an issue first in case there were objections to having this feature.

**Comment by ericmj** [comment]
Global configs like this are not recommended because they can have unexpected side effects. For example you can have a dependency that connects to a service that requires the default certificates and the global config would break that dependency.

Mint does not have any global options and since it's a low level library we would like to avoid adding them.

**Comment by bfad** [comment]
I thought you might object to adding something like this, which is why I figured I would ask through the issues before doing the work to implement it.
