### ISSUE TITLE
Header non-string values

### ISSUE THREAD

**Issue by egze** [elixir-mint/mint#235]
I'm using mojito (which is based on Mint) as a Http client for ExAws.

```elixir
defmodule MyApp.S3.HttpClient do
  @behaviour ExAws.Request.HttpClient
  def request(method, url, body, headers, http_opts \\ []) do
    Mojito.request(method, url, headers, body, http_opts)
  end
end
```

When trying to download a file, I'm getting:
```
error] GenServer #PID<0.637.0> terminating
** (FunctionClauseError) no function clause matching in Mint.HTTP1.Request."-validate_header_value!/2-lc$^0/1-0-"/1

Last message (from #PID<0.478.0>): {:request, %Mojito.Request{body: "", headers: [{"Authorization", "AWS4-HMAC-SHA256 Credential=5634563456/345634564/eu-central-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature= e3b04442v8fc1c149afbf4c8996fb92427ae41e4649b934cag95991b7852b855"}, {"host", "s3.eu-central-1.amazonaws.com"}, {"x-amz-date", "20191213T171338Z"}, {"content-length", 0}, {"x-amz-content-sha256", "e3b04442v8fc1c149afbf4c8996fb92427ae41e4649b934cag95991b7852b855"}], method: :head, opts: [], url: "https://s3.eu-central-1.amazonaws.com/bucket/file"}, #PID<0.478.0>, #Reference<0.938540534.2258632705.207122>}
State: %{conn: nil, hostname: nil, port: nil, protocol: nil, reply_tos: %{}, response_refs: %{}, responses: %{}}
Client #PID<0.478.0> is alive
```

This is happening because of this part `{"content-length", 0}`, if I preprocess the headers and convert the values to strings, then it works.

I want to fix it, and I think Mint is the right place to do it. What do you think? I will provide a PR.

**Comment by ericmj** [comment]
Is that the full error message? It is missing the stacktrace and therefor the arguments that caused the FunctionClauseError.

Mint expects the headers as strings so you need to convert to that first. We should not automatically try to convert everything to strings.

**Comment by egze** [comment]
I think the library can be more user friendly if it is possible. Please think about it, hopefully you change your mind.

But if not, then I can always fix it in mojito. It‘s not a problem.

**Comment by ericmj** [comment]
Accepting more types is not always more user friendly. For example if you pass `{"content-length", [48, 49, 50]}` as a header would you want that to be silently accepted and converted to a string by Mint? A good example of this is Javascript where the automatic type coercion is known to cause many issues.

Mint is a low level library so it should be strict in its input. One reason is because it is very important that Mint is correct and should not be doing anything unexpected or confusing since it will be wrapped by many libraries. The smaller the API surface the less complex it will be. Another reason is because the type conversions are costly. If Mint is wrapped by Mojito, which is wrapped by Tesla and used in ExAWS and they all try to convert headers to strings we are wasting a lot of cycles.

If you think headers should be automatically converted to strings (I am not sure I agree) it should be done at the boundaries which would be in Mojito or even better before you call Mojito.

**Comment by whatyouhide** [comment]
> Mint is a low level library so it should be strict in its input. One reason is because it is very important that Mint is correct and should not be doing anything unexpected or confusing since it will be wrapped by many libraries. The smaller the API surface the less complex it will be.

This ☝️, this is not Mint's responsibility. Please open this issue in Mojito (which is much higher level ) if you believe the library should do this, but I agree with Eric, probably you should do it before calling any library :). Headers are strings in the HTTP protocol, so trying to pass other things can cause all kinds of subtle behaviours.

Thanks for the issue!
