### ISSUE TITLE
Question about caching certificates

### ISSUE THREAD

**Issue by vrcca** [elixir-mint/mint#274]
Hello!

I am building this load testing app which basically boots 100k processes and each of these try every few seconds to publish a message to a SNS topic. Investigating the bottlenecks, I noticed that this line starts to be a problem with lots of msgs getting queued for IO trying to read the cacert file: https://github.com/elixir-mint/mint/blob/master/lib/mint/core/transport/ssl.ex#L550

I was wondering if this would be a good way to cache this IO? 

```elixir
defmodule LoadGenerator.Infrastructure.HttpClient do
  # preloads 
  @ca_certs CAStore.file_path()
            |> File.read!()
            |> :public_key.pem_decode()
            |> Enum.filter(fn cert -> match?({:Certificate, _, :not_encrypted}, cert) end)
            |> Enum.map(fn cert -> :public_key.pem_entry_decode(cert) end)

  def child_spec(pool_size) do
    conn_opts = [
      transport_opts: [partial_chain: &Mint.Core.Transport.SSL.partial_chain(@ca_certs, &1)]
    ]

    {Finch,
     name: FinchClient,
     pools: %{
       :default => [size: pool_size, conn_opts: conn_opts]
     }}
  end
end
```

I am hoping that this way I will have the certificates preloaded in memory.

Thanks!

**Comment by ericmj** [comment]
I would think that would be a good way to cache it. But I would suggest benchmarking it.

**Comment by vrcca** [comment]
Thanks!

**Comment by chulkilee** [comment]
Having another cache later on the top of CAStore is against the purpose CAstore - which is responsible to keep the cacert file up-todate.

Instead of letting libraries or users to add cache, the ideal way is

- Let `CAstore` have a function to return up-to-date ca certs with caching in it (so it avoid file IO *and* invalidate the cache when ca is updated)
- Let Erlang `:ssl` take function to return cacert (currently it accepts only `cacerts` and `cacertfile`), so that all libraries can just pass the function, not evaluating them when needed.

Alternatively, we can add the first part, and let mint call the function instead of reading the file.

**Comment by ericmj** [comment]
I have created a PR that adds caching to cacertfile: https://github.com/elixir-mint/mint/pull/275.

> Let Erlang :ssl take function to return cacert (currently it accepts only cacerts and cacertfile), so that all libraries can just pass the function, not evaluating them when needed.

Erlang already caches cacertfile on their end so I don't think a function is needed.
