### ISSUE TITLE
Should mint be responsible for error handling empty address?

### ISSUE THREAD

**Issue by sato11** [elixir-mint/mint#351]
Taking a look into https://github.com/sneako/finch/issues/186, I've found the case where `:gen_tcp.connect/4` throws `:badarg` which mint is unable to handle. Is it in mint's scope to take care of it? Personally I'd find it great if it was since I feels that zero byte strings are not inconsistent with `Mint.Types.address()` which contains `String.t()`. What do you think?

```elixir
iex(31)> Mint.HTTP.connect(:http, "httpbin.org", 80)  
{:ok,
 %Mint.HTTP1{
   buffer: "",
   host: "httpbin.org",
   mode: :active,
   port: 80,
   private: %{},
   proxy_headers: [],
   request: nil,
   requests: {[], []},
   scheme_as_string: "http",
   socket: #Port<0.9>,
   state: :open,
   streaming_request: nil,
   transport: Mint.Core.Transport.TCP
 }}
iex(32)> Mint.HTTP.connect(:http, "httpbin.void", 80)
{:error, %Mint.TransportError{reason: :nxdomain}}
iex(33)> Mint.HTTP.connect(:http, "", 80)            
** (exit) :badarg
    (kernel 8.3.1) gen_tcp.erl:218: :gen_tcp.connect/4
    (mint 1.4.0) lib/mint/core/transport/tcp.ex:41: Mint.Core.Transport.TCP.connect/3
    (mint 1.4.0) lib/mint/http1.ex:115: Mint.HTTP1.connect/4
```

**Comment by wojtekmach** [comment]
I believe the problem is not that Mint crashes for this value but that the reason is very opaque. A common solution is add additional information i accordance with https://www.erlang.org/eeps/eep-0054. Given it is an exit we cannot do that though. So unfortunately I don’t think Mint can do much about it. (It could special case `""` but eg `"/(*"` would be invalid too.) I think the real fix would have to happen in OTP.

**Comment by sato11** [comment]
Hi, thanks for the feedback and the link. I had a feeling that this is maybe OTP issue, but I was not very sure about it and asked here beforehand. But thanks to your comment I guess it's making sense to me. I'll be reporting it in OTP after a little more research. Thanks a lot!
