### ISSUE TITLE
HTTP/3

### ISSUE THREAD

**Issue by ckoch-cars** [elixir-mint/mint#379]
What would be involved in extending mint for HTTP/3 support? 
Would this require changes mostly in this library, or would it require change in the underlying erlang libraries?

**Comment by ericmj** [comment]
The first step would be to implement the underlying transport protocol QUIC. I believe this could be built as a separate library and doesn't have to be part of Erlang/OTP.

**Comment by whatyouhide** [comment]
Hey @ckoch-cars, the problem with HTTP/3 is that the underlying transport layer protocol is different as well (UDP + QUIC instead of TCP/SSL). I’m not sure the best approach is to start with HTTP/3 support directly in Mint: maybe we can try an HTTP/3-only client that mirrors how Mint is architected, and then figure out what it would take to bring it back into Mint?

**Comment by ericmj** [comment]
I suggest we close this for now since it's currently not planned and requires work outside of Mint before implementation can start.
