### ISSUE TITLE
Discussion: basic authorization

### ISSUE THREAD

**Issue by ndrean** [elixir-mint/mint#385]
I don't see how you set `curl -u user:pwd` with Mint in the docs.
Using header. =`[Authorization:  Bearer #{Base.encode64("user:pass")} ]` does not work

**Comment by whatyouhide** [comment]
Hey @ndrean, `-u` in curl is a convenience over headers as you said. As [per Wikipedia](https://en.wikipedia.org/wiki/Basic_access_authentication), for example, you need to use the `Authorization` but use `Basic` generally rather than `Bearer`:

```elixir
{"authorization", "Basic #{Base.encode64("<username>:<password>")}"}
```

We don't plan to support conveniences over authentication methods such as this one in Mint, since the client is intended to be low level.

Thanks!
